[2025-09-20T18:59:25.328+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-20T18:59:25.387+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-09-20T18:59:25.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-02T00:00:00+00:00 [queued]>
[2025-09-20T18:59:25.417+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-09-20T18:59:25.462+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_load_fact_Invoices> on 2024-01-02 00:00:00+00:00
[2025-09-20T18:59:25.476+0000] {standard_task_runner.py:72} INFO - Started process 237 to run task
[2025-09-20T18:59:25.494+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'bronze_full_load_spaceparts_optimized', 'extract_load_fact_Invoices', 'scheduled__2024-01-02T00:00:00+00:00', '--job-id', '182', '--raw', '--subdir', 'DAGS_FOLDER/01_Bronce.py', '--cfg-path', '/tmp/tmp6hik6m3r']
[2025-09-20T18:59:25.503+0000] {standard_task_runner.py:105} INFO - Job 182: Subtask extract_load_fact_Invoices
[2025-09-20T18:59:26.137+0000] {task_command.py:467} INFO - Running <TaskInstance: bronze_full_load_spaceparts_optimized.extract_load_fact_Invoices scheduled__2024-01-02T00:00:00+00:00 [running]> on host 050d5b6b4fc2
[2025-09-20T18:59:26.337+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='bronze_full_load_spaceparts_optimized' AIRFLOW_CTX_TASK_ID='extract_load_fact_Invoices' AIRFLOW_CTX_EXECUTION_DATE='2024-01-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-02T00:00:00+00:00'
[2025-09-20T18:59:26.338+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-09-20T18:59:26.364+0000] {01_Bronce.py:385} INFO - Starting optimized extraction for table: fact.Invoices
[2025-09-20T18:59:29.341+0000] {01_Bronce.py:398} INFO - Table fact.Invoices has 18,459,441 rows
[2025-09-20T18:59:29.342+0000] {01_Bronce.py:420} INFO - Using chunk size: 15,000 for 18,459,441 rows
[2025-09-20T18:59:29.343+0000] {01_Bronce.py:425} INFO - Starting streaming extraction and load for fact.Invoices
[2025-09-20T18:59:33.105+0000] {01_Bronce.py:235} INFO - Processing chunk 1 with 15000 rows
[2025-09-20T18:59:33.153+0000] {01_Bronce.py:298} ERROR - Error creating table bronze_fact_invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:59:33.153+0000] {01_Bronce.py:360} ERROR - Error in streaming load to bronze_fact_invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:59:33.153+0000] {01_Bronce.py:445} ERROR - Error processing table fact.Invoices: 'Connection' object has no attribute 'commit'
[2025-09-20T18:59:33.165+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 427, in extract_and_load_table_optimized
    records_loaded = loader.load_data_streaming(data_iterator, bronze_table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 343, in load_data_streaming
    column_mapping = self.create_table_if_not_exists(chunk, table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 292, in create_table_if_not_exists
    conn.commit()
AttributeError: 'Connection' object has no attribute 'commit'
[2025-09-20T18:59:33.175+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=bronze_full_load_spaceparts_optimized, task_id=extract_load_fact_Invoices, run_id=scheduled__2024-01-02T00:00:00+00:00, execution_date=20240102T000000, start_date=20250920T185925, end_date=20250920T185933
[2025-09-20T18:59:33.211+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-09-20T18:59:33.211+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 182 for task extract_load_fact_Invoices ('Connection' object has no attribute 'commit'; 237)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/dags/01_Bronce.py", line 427, in extract_and_load_table_optimized
    records_loaded = loader.load_data_streaming(data_iterator, bronze_table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 343, in load_data_streaming
    column_mapping = self.create_table_if_not_exists(chunk, table_name)
  File "/opt/airflow/dags/01_Bronce.py", line 292, in create_table_if_not_exists
    conn.commit()
AttributeError: 'Connection' object has no attribute 'commit'
[2025-09-20T18:59:33.255+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-20T18:59:33.267+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
